### ISSUE TITLE
Text gets weird background

### ISSUE THREAD

**Issue by michaelrkn** [baicunko/scanyourpdf#12]
Love this tool, thanks for building it! I noticed that when I save a document as PDF and upload it, the text gets a weird background. Check out this [original file](https://github.com/baicunko/scanyourpdf/files/5478409/original.pdf) and the [processed](https://github.com/baicunko/scanyourpdf/files/5478410/processed.pdf) version for example. Thanks for looking into this!

**Comment by michaelrkn** [comment]
I figured out that this is caused by the `+noise Multiplicative` argument. Using Gaussian, Laplacian, or Uniform produced better results for me.

**Comment by baicunko** [comment]
Thanks. I'm currently working on improving the code and this will be included!
